site_name: Crear una aplicación FullStack con MySQL, SpringBoot y ReactJS
nav:
  - Inicio: index.md
  - Introducción: intro.md
  - Base de datos: basedatos.md
  - Backend API - Parte1: backendp1.md
  - Backend API - Parte2: backendp2.md
  - Backend API - Parte3: backendp3.md
  - Backend API - Parte4: backendp4.md
  - Backend API - Parte5: backendp5.md
theme:
  name: readthedocs
site_dir: docs_site